spring:
  application:
    name: springboot-web

app:
  id: springboot-web

env: dev

# apollo
apollo:
  meta: http://127.0.0.1:8080
  bootstrap:
    #在应用启动阶段，向Spring容器注入被托管的application.properties文件的配置信息。
    enabled: true
    #将Apollo配置加载提到初始化日志系统之前。
    eagerLoad:
      enabled: true
